// Lifts the Temperament Sticker Kit into the repo. Re-run whenever the kit
// changes:  node app/personal-definition/_assets/mascot/kit/extract-kit.mjs "<path to kit html>"
// Outputs are committed; do not hand-edit them.
import fs from "node:fs";
import path from "node:path";

const kitPath = process.argv[2];
if (!kitPath) throw new Error("usage: extract-kit.mjs <Temperament Sticker Kit.html>");
const kit = fs.readFileSync(kitPath, "utf8");
const root = "app/personal-definition";

// 1. Eight pose webps, from the kit's POSE = {"1": "data:…", …} table.
const poses = [...kit.matchAll(/"(\d)":\s*"data:image\/webp;base64,([A-Za-z0-9+/=]+)"/g)];
if (poses.length !== 8) throw new Error(`expected 8 poses, got ${poses.length}`);
for (const [, n, b64] of poses) {
  fs.writeFileSync(path.join(root, "_assets/mascot/kit", `pose-${n}.webp`), Buffer.from(b64, "base64"));
}

// 2. Card CSS: the shared frame + the four temperament blocks, as one module.
const blocks = [...kit.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)]
  .map((m) => m[1])
  .filter((c) => /^\s*\/\* (Shared frame|ANALYSTS|DIPLOMATS|SENTINELS|EXPLORERS)/.test(c));
if (blocks.length !== 5) throw new Error(`expected 5 card style blocks, got ${blocks.length}`);
const css = blocks
  .join("\n")
  // No web fonts in this app: kit display/body fonts inherit font-momo-trust,
  // mono and graffiti fall back to platform stacks.
  .replaceAll('"JetBrains Mono", monospace', 'ui-monospace, Menlo, monospace')
  .replaceAll('"Fredoka", sans-serif', "inherit")
  .replaceAll('"Be Vietnam Pro", sans-serif', "inherit")
  .replaceAll('"Bungee", Impact, sans-serif', 'Impact, "Arial Black", sans-serif');
if (/JetBrains|Fredoka|Be Vietnam|Bungee/.test(css)) throw new Error("unreplaced kit font left in CSS");
// Audit: the only element whose resting (non-animated) state is hidden is the
// Sentinel tick (dashoffset 24, revealed by st-draw). Everything else rests visible
// (hearts/stars/etc. only vary opacity or scale mid-animation). Pin ticks to their
// fully drawn end state wherever animation is stopped.
const capture = `
/* Added by extract-kit.mjs: a capture records one frame, and reduced motion
   wants a still one, so pin everything to a complete rest (mirrors
   mascot.module.css). Ticks are hidden at rest and drawn only by st-draw, so
   they are pinned to their end state. */
@media (prefers-reduced-motion: reduce) {
  .stk--sentinel .tick { stroke-dashoffset: 0 !important; }
  .stk { transition: none !important; transform: none !important; }
}
:global([data-capturing]) .stk *,
:global([data-capturing]) .stk::before,
:global([data-capturing]) .stk::after { animation: none !important; transition: none !important; }
:global([data-capturing]) .stk { transition: none !important; transform: none !important; }
:global([data-capturing]) .stk--sentinel .tick { stroke-dashoffset: 0 !important; }
`;
fs.writeFileSync(
  path.join(root, "_components/result/sticker.module.css"),
  `/* GENERATED by _assets/mascot/kit/extract-kit.mjs from the Temperament Sticker Kit. Do not edit by hand. */\n${css}\n${capture}`,
);

// 3. Scene SVG: the back and front layer of each temperament's hero card.
const KIT_TO_ID = { analyst: "analysts", diplomat: "diplomats", sentinel: "sentinels", explorer: "explorers" };
const scenes = {};
for (const m of kit.matchAll(/<div class="stk stk--(analyst|diplomat|sentinel|explorer)"[^>]*data-hero[^>]*>/g)) {
  const layer = (name) => {
    const open = `<svg class="stk__layer stk__${name}" viewBox="0 0 300 360" aria-hidden="true">`;
    const start = kit.indexOf(open, m.index);
    if (start < 0) throw new Error(`${m[1]}: ${name} layer not found with the expected opening tag`);
    const end = kit.indexOf("</svg>", start);
    return kit
      .slice(start + open.length, end)
      .replace(/<!--[\s\S]*?-->/g, "")
      .replace(/(<text[^>]*data-tag[^>]*>)[^<]*/g, "$1{{TAG}}")
      .replace(/\s+\n/g, "\n")
      .trim();
  };
  scenes[KIT_TO_ID[m[1]]] = { back: layer("back"), front: layer("front") };
}
if (Object.keys(scenes).length !== 4) throw new Error(`expected 4 scenes, got ${Object.keys(scenes).length}`);
if (!scenes.explorers.front.includes("{{TAG}}")) throw new Error("explorers tag placeholder missing");
fs.writeFileSync(
  path.join(root, "_components/result/stickerScenes.ts"),
  `// GENERATED by _assets/mascot/kit/extract-kit.mjs from the Temperament Sticker Kit. Do not edit by hand.
// Inner markup of each temperament card's back and front SVG layers. Class
// names are the kit's; StickerCard maps them to sticker.module.css at runtime.
import type { TemperamentId } from "../../_lib/temperament";

export const SCENES: Record<TemperamentId, { back: string; front: string }> = ${JSON.stringify(scenes, null, 2)};
`,
);
console.log("ok: 8 poses, card CSS, 4 scenes");
